version: '3'
services:
  # app-name-container:
  #   container_name: app-name
  #   build:
  #     context: . 
  #     dockerfile: ./Dockerfile
  #   env_file:
  #     - .env
  #   networks:
  #     - app-name-network
  alarm-mysql:
    container_name: alarm-mysql
    image: mysql:5.7
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'alarmdb'
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_ROOT_HOST: 'localhost'
    ports: 
      - '3360:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks: 
      - app-name-network

networks:
  app-name-network:

volumes:
  db_data:
